export default [
    {   
    id : 1,  
    name : "Hedy Lamarr ",
    dates : "1914 - 2000",
    domain : "Technology",
    pictureUrl : "https://cdn.pixabay.com/photo/2013/05/15/00/44/hedy-lamarr-111272_1280.jpg",
    },
    
    {
    id:2,
    name : "Hypatie",
    dates : "355 - 415",
    domain : "Mathematics, Astronomy, Inventor",
    pictureUrl : "https://curiokids.net/wp-content/uploads/2019/12/Hypatie_curiokids.jpg.webp",
    },

    
    {id : 3,
    name : "Marie Curie",
    dates : "1867 - 1934",
    domain : "Nuclear Physics, Chemistry",
    pictureUrl : "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Mariecurie.jpg/791px-Mariecurie.jpg",
    },

    {id:4,
    name : "Rosalind Franklin",
    dates : "1920 - 1958",
    domain : "Chemistry, Physics, Biology ",
    pictureUrl : "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Rosalind_Franklin.jpg/499px-Rosalind_Franklin.jpg?20180422194635",
    },

    {id:5,
    name : "Ada Lovelace",
    dates : "1815 - 1852",
    domain : "Mathematics, Computer science ",
    pictureUrl : "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Ada_Lovelace_1838.jpg/481px-Ada_Lovelace_1838.jpg",
    },

    {id: 6,
    name: "Jane Goodall",
    dates: "1934 - ",
    domain: "Ethology, Anthropology",
    pictureUrl: "https://st2.depositphotos.com/5326338/11438/i/450/depositphotos_114384144-stock-photo-primatologist-dr-jane-goodall.jpg",
    },  

    {id: 7,
    name: "Tapputi-Belet-ekalle",
    dates: "XIII BC",
    domain: "Chemistry",
    pictureUrl: "https://deathscent.com/wp-content/uploads/2022/06/ekwnr8rwnrwz-1-e1655660244452.jpg",
    },  
    {id: 8,
    name: "Théano",
    dates: "VI BC",
    domain: "Philosophy, Mathematics",
    pictureUrl: "https://miro.medium.com/v2/resize:fit:468/1*uMAPVMDRhnKTfl0qmW0aOQ.jpeg",
    },

    {id: 9,
        name: "Lise Meitner",
        dates: "1878 - 1968",
        domain: "Nuclear Physics",
        pictureUrl: "https://www.taurillon.org//IMG/logo/arton13775.jpg?1605873970",
       },  
       
       {id: 10,
        name: "Dorothy Hodgkin",
        dates: "1910 - 1994",
        domain: "Biochemistry",
        pictureUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIVUagu9VpoO7QH0WaZevkBjSSJ9z6bcT0_A&s",
       },  
       
       {id: 11,
        name: "Chien-Shiung Wu",
        dates: "1912 - 1997",
        domain: "Physics",
        pictureUrl: "https://images.newscientist.com/wp-content/uploads/2019/06/05113158/50546367.jpg",
       },  
       
       {id: 12,
        name: "Barbara McClintock",
        dates: "1902 - 1992",
        domain: "Genetics",
        pictureUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMzoa8BpAY05K6bdTlq0eKN4gi0KbdP-FxoA&s",
       },  
       
       {id: 13,
        name: "Vera Rubin",
        dates: "1928 - 2016",
        domain: "Astronomy",
        pictureUrl: "https://www.cieletespace.fr/media/default/0001/14/C0nmqS3XcAAi98K-5861.jpeg",
       },  
       
       {id: 14,
        name: "Maria Sibylla Merian",
        dates: "1647 - 1717",
        domain: "Entomology, Illustration",
        pictureUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPXt3A-ZMsYM66GUZk67pyUDNJbu3t4WsSmQ&s",
       },  
       
       {id: 15,
        name: "Rachel Carson",
        dates: "1907 - 1964",
        domain: "Marine Biology, Ecology",
        pictureUrl: "https://www.omnesmag.com/wp-content/uploads/2024/12/CULTURA.jpg",
       },  
       
       {id: 16,
        name: "Henrietta Swan Leavitt",
        dates: "1868 - 1921",
        domain: "Astronomy",
        pictureUrl: "https://cdn.britannica.com/66/158566-004-EBCD4212/Henrietta-Swan-Leavitt.jpg",
       },
       {id: 17,
        name: "Emmy Noether",
        dates: "1882 - 1935",
        domain: "Mathematics, Physics",
        pictureUrl: "https://opinion-images.wsj.net/im-80191927/?width=1280&size=1",
       },  
       
       {id: 18,
        name: "Mary Anning",
        dates: "1799 - 1847",
        domain: "Paleontology",
        pictureUrl: "https://www.mnhn.fr/system/files/2024-05/banniere-portrait-mary-anning-natural-history-museum-londres.jpg",
       },  
       
       {id: 19,
        name: "Florence Nightingale",
        dates: "1820 - 1910",
        domain: "Statistics, Nursing",
        pictureUrl: "https://static.nationalgeographic.fr/files/styles/image_3200/public/florence-nightingale-facts-featured.jpg?w=1900&h=1330",
       },  
       
       {id: 20,
        name: "Gerty Cori",
        dates: "1896 - 1957",
        domain: "Biochemistry",
        pictureUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRg-CPPk-p_b57YJkedr4j43cj1d2iJ_If9kQ&s",
       },  
       
       {id: 21,
        name: "Katherine Johnson",
        dates: "1918 - 2020",
        domain: "Mathematics, Space Science",
        pictureUrl: "https://www.sciencesetavenir.fr/assets/img/2020/02/24/cover-r4x3w1200-5e540fed761ec-1966-l-06717.jpg",
       },  
       
       {id: 22,
        name: "Tu Youyou",
        dates: "1930 - ",
        domain: "Pharmacology, Medicine",
        pictureUrl: "https://www.swissinfo.ch/content/wp-content/uploads/sites/13/2015/10/7a4b32376430ddcf199d4f6a17ceb1ca-258018896-jpg-data.jpg?ver=08fe73b1",
       },  
       
       {id: 23,
        name: "Margaret Hamilton",
        dates: "1936 - ",
        domain: "Computer Science",
        pictureUrl: "https://etudestech.com/wp-content/uploads/2023/07/capture-decran-2023-07-05-144307.png",
       },  
       
       {id: 24,
        name: "Irène Joliot-Curie",
        dates: "1897 - 1956",
        domain: "Chemistry, Physics",
        pictureUrl: "https://www.humanite.fr/wp-content/uploads/2019/08/p20_irene_joliot-curie_ven_1.jpg?w=1200",
       },  
       
       {id: 25,
        name: "Annie Jump Cannon",
        dates: "1863 - 1941",
        domain: "Astronomy",
        pictureUrl: "https://lirp.cdn-website.com/f225c1ca/dms3rep/multi/opt/AJumpCannon-640w.jpg",
       },  
       
       {id: 26,
        name: "Sophie Germain",
        dates: "1776 - 1831",
        domain: "Mathematics, Physics",
        pictureUrl: "https://www.numerama.com/wp-content/uploads/2022/03/sophiegermain022.jpg",
       },  
       
       {id: 27,
        name: "Rosalyn Yalow",
        dates: "1921 - 2011",
        domain: "Medical Physics",
        pictureUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Rosalyn_Yalow.jpg",
       },  
       
       {id: 28,
        name: "Maria Goeppert Mayer",
        dates: "1906 - 1972",
        domain: "Physics",
        pictureUrl: "https://images.ctfassets.net/eqlypemzu8y5/6AirqmcJcGJWvTNLNHazQl/b29e5f6126a01526ac1efb298875692f/Maria_Goeppert_Mayer.jpg",
       },  
       
       {id: 29,
        name: "Ada Yonath",
        dates: "1939 - ",
        domain: "Chemistry, Structural Biology",
        pictureUrl: "https://www.weizmann-france.com/wp-content/uploads/Ada-Yonath-3.jpg",
       },  
       
       {id: 30,
        name: "Jane Marcet",
        dates: "1769 - 1858",
        domain: "Chemistry, Science Education",
        pictureUrl: "https://www.sciencehistory.org/wp-content/uploads/2023/04/marcet_profile-1.jpg",
       },  
       
       {id: 31,
        name: "Esther Lederberg",
        dates: "1922 - 2006",
        domain: "Microbiology, Genetics",
        pictureUrl: "https://upload.wikimedia.org/wikipedia/commons/1/15/Esther_Lab.jpg",
       },
       {id: 32,
        name: "Enheduanna",
        dates: "2285 - 2250 BC",
        domain: "Astronomy, Mathematics",
        pictureUrl: "https://www.slate.fr/uploads/store/story_178194/medium_landscape_178194.jpg",
       },  
       
       {id: 33,
        name: "Aglaonice",
        dates: "II BC",
        domain: "Astronomy",
        pictureUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQte_Yp6S8kk3RyAZwPoeluL4GxSbXg9GbK9Q&s",
       },  
       
       {id: 34,
        name: "Merit-Ptah",
        dates: "2700 BC",
        domain: "Medicine",
        pictureUrl: "https://histoireparlesfemmes.com/wp-content/uploads/2018/01/femme-c3a9gyptienne.jpg?w=640",
       },  
       
       {id: 35,
        name: "Pandrosion",
        dates: "IV century AD",
        domain: "Mathematics",
        pictureUrl: "https://image.jimcdn.com/app/cms/image/transf/dimension=1040x10000:format=jpg/path/s2217cd0bb1220415/image/i4c8bf8027aa3fad4/version/1713058714/ancient-alexandria.jpg",
       },   
           
  ];